### ISSUE TITLE
GitBot token for publish changelogs  on github 

### ISSUE THREAD

**Issue by deveshbajaj** [relekang/python-semantic-release#150] opened 2019-09-18 11:48 UTC
using gitbot access token to publish changelog, as it will be handy to use bot token CI  server.

**Comment by relekang** [comment] 2019-09-18 15:27
I do not understand this issue. Can you elaborate?

**Comment by deveshbajaj** [comment] 2019-09-19 09:42
I am trying to implement semantic versioning on my repo as, made a gitbot to do all of my GitHub related automation, as I was storing $GH_TOKEN with my gitbot access token to publish the release. but it start throwing an error. so, for now, i am using the personal token. But it will be a good feature to allow to bot  release to release feature

**Comment by alandtse** [comment] 2020-01-15 09:14
I think it's a dupe of [this](https://github.com/relekang/python-semantic-release/issues/109#issuecomment-536264768). The default GH_TOKEN from GitHub does not have the access rights necessary so a personal token has to be issued.

**Comment by relekang** [comment] 2020-01-18 16:02
Closing this since it seems this is a problem with the token and not this project.

**Closed by relekang** 2020-01-18 16:02 UTC
