### ISSUE TITLE
Add support for Github actions

### ISSUE THREAD

**Issue by relekang** [relekang/python-semantic-release#109] opened 2019-02-08 08:27 UTC
- [x] Add necessary checks for github actions.
- [x] Setup github actions for releasing this project by calling on the current source code.
- [x] Add to the documentation how to setup semantic release with github actions.

**Comment by relekang** [comment] 2019-09-14 15:13
It would be awesome if you have the time to create a PR for it 😄

**Comment by iamogbz** [comment] 2019-09-16 11:37
@relekang also I had temporarily fixed this in my CI by appending `.git` to the origin but had some other issues that prevented me from using the package e.g. `--noop` still pushing tags etc. I will create issues as I don't think those are github actions specific.

**Comment by alandtse** [comment] 2019-09-29 06:43
I'm testing the merged version and using `GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}` which uses the default GITHUB_TOKEN. This results in the following error while trying to push:
 
```
stderr: 'fatal: could not read Password for 'https://[AUTH_TOKEN]@github.com': No such device or address'
```
I believe the problem is the default `GITHUB_TOKEN` expects to be used with a `GITHUB_ACTOR` as the username. I'm basing this observation on this [code](https://github.com/mikeal/publish-to-github-action/blob/master/entrypoint.sh#L10). 

I'll play around and see if it's as simple as adding `GITHUB_ACTOR` as the user in the https string.

**Comment by alandtse** [comment] 2019-09-29 07:53
I ended up getting farther with my [repo changes](https://github.com/relekang/python-semantic-release/compare/master...alandtse:master). However, ran into a branch protection issue. 
```
stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.        
```
I wasn't sure if the problem was because I'm committing to an organization, so I gave up with the `GITHUB_TOKEN` _(I'm an admin on the repo I'm pushing to so not sure why the `GITHUB_TOKEN` isn't enough to log in as my account and didn't want to debug it further)_ and created a personal access token.  With that I was able to commit using my changes.
  
**However**, I don't know if my changes are necessary with a personal access token so I'm leaving this comment in case someone wants to try the code with a `GITHUB_TOKEN`.  If it works, happy to do a PR or you can just integrate my code directly.

**Comment by AlphaMycelium** [comment] 2020-01-16 08:10
@alandtse I've tried your changes with a `GITHUB_TOKEN`, and can confirm that it works correctly.

**Comment by alandtse** [comment] 2020-01-16 08:21
@AlphaMycelium Great, I'll put in a PR.

**Comment by AlphaMycelium** [comment] 2020-01-17 19:42
With the new `GITHUB_ACTOR` checks, I have been able to create a working GitHub Action [here](https://github.com/AlphaMycelium/psr-action), if anyone is interested in taking a look. I haven't tested it with every possible configuration.

**Comment by AlphaMycelium** [comment] 2020-01-25 10:57
One problem I'm having is that the release notes are replaced with a short message containing only the name of the tag, as seen [here](https://github.com/AlphaMycelium/chicken-nuggets/releases/tag/v1.0.1). I'm not quite sure what is causing this, but it only happens when running from GitHub Actions.

https://github.com/AlphaMycelium/psr-action/issues/1

**Comment by relekang** [comment] 2020-01-25 11:51
It is not replaced, that tag is missing release notes so it is showing the annotated message from the git tag. If you view the list of tags in github it shows which have release notes and which does not. My guess is that the upload of changelog failed.

**Comment by AlphaMycelium** [comment] 2020-01-25 17:11
Ah, makes sense. In that case, what could be causing it to fail? Insufficient permissions? It says [on the GitHub Actions help page][token_perms] that the provided token has write access for `contents`, which allows posting release notes as listed [here][contents].

[token_perms]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token
[contents]: https://developer.github.com/v3/apps/permissions/#permission-on-contents

**Comment by relekang** [comment] 2020-01-27 14:52
Maybe set the `DEBUG=*` environment variable and check the logs?

**Comment by AlphaMycelium** [comment] 2020-01-29 16:18
Here's the relevant section of the logs with debugging enabled (full logs [here](https://github.com/AlphaMycelium/chicken-nuggets/runs/415415535?check_suite_focus=true) if necessary). I can't see any obvious errors at first glance.

```
Updating changelog
New release published
Wed, 29 Jan 2020 16:13:24 GMT semantic_release:hvcs 'get_hvcs: hvcs=' 'github' +7.6s
Wed, 29 Jan 2020 16:13:24 GMT semantic_release:history:logs 'generate_changelog("1.0.2", "1.1.0")' +7.6s
Wed, 29 Jan 2020 16:13:24 GMT semantic_release:history:logs 'markdown_changelog(version="1.1.0", header=False, changelog=...)' +4.5ms
Wed, 29 Jan 2020 16:13:24 GMT semantic_release:hvcs 'post_changelog(owner=AlphaMycelium, repository=chicken-nuggets, version=1.1.0)' +4.7ms
Wed, 29 Jan 2020 16:13:24 GMT semantic_release:hvcs 'get_hvcs: hvcs=' 'github' +81.25us
Wed, 29 Jan 2020 16:13:24 GMT semantic_release:hvcs:github 'listing releases' +0.0us
Wed, 29 Jan 2020 16:13:24 GMT semantic_release:hvcs:github 'response #1, status_code=201, status=True' +319.0ms
```

**Comment by relekang** [comment] 2020-01-30 07:13
Looks like we need to add some more logging for this.

**Comment by KingDarBoja** [comment] 2020-02-11 16:30
Hey @AlphaMycelium, can you provide a example with multiple projects on the same repo? Cheers!

**Comment by AlphaMycelium** [comment] 2020-02-12 15:48
@KingDarBoja Why are you trying to change `GITHUB_WORKFLOW`? Also, I think I've worked out a simple way to handle multiple projects, should be quick to implement.

**Comment by KingDarBoja** [comment] 2020-02-12 15:52
@AlphaMycelium Thanks for the quick response, I was expecting to change the path to were the project is being stored as the docker build is always pointing to the root dir, hence, making it impossible to find the `setup.cfg` file with the `[semantic-release]` settings.

**Comment by AlphaMycelium** [comment] 2020-02-12 15:56
@KingDarBoja I see, I'm thinking the easiest way to do this is to pass a subdirectory as an input and `cd` into it as part of the entrypoint script. Then to run for multiple projects you can just repeat the step with a different directory.

I'll implement that quickly and push it to a branch for you to try.

**Comment by AlphaMycelium** [comment] 2020-02-12 16:08
@KingDarBoja Ok, it's on a branch called [`monorepo`](https://github.com/AlphaMycelium/psr-action/tree/monorepo). Give that a try and see if it works, if so I'll add some docs and release it to the marketplace.

```yaml
    - name: Release Project 1
      uses: AlphaMycelium/psr-action@monorepo
      with:
        directory: ./project1
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_username: <ADD YOUR USERNAME HERE>
        pypi_password: ${{ secrets.PYPI_PASSWORD }} 
    
    - name: Release Project 2
      uses: AlphaMycelium/psr-action@monorepo
      with:
        directory: ./project2
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_username: <ADD YOUR USERNAME HERE>
        pypi_password: ${{ secrets.PYPI_PASSWORD }} 
```

**Comment by KingDarBoja** [comment] 2020-02-14 14:46
@AlphaMycelium Hi mate, just tested it and now it was able to cd to the correct dir, however, now I am facing some error that I think isn't related to the actions but semantic release:

```console
Current version: 1.0.0
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:cli 'main args:' {'force_level': None, 'post': False, 'retry': False, 'noop': False, 'define': ()} +0.0us
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:cli 'main env:' 'PYPI_USERNAME="",PYPI_PASSWORD="",GH_TOKEN="$GH_TOKEN",GL_TOKEN="None",' +68.75us
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:cli 'main config:' {'check_build_status': 'false', 'commit_message': 'Automatically generated by python-semantic-release', 'commit_parser': 'semantic_release.history.angular_parser', 'patch_without_tag': 'false', 'upload_to_pypi': 'false', 'version_source': 'commit'} +84.5us
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:history 'get_current_version_by_config_file' +0.0us
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:history 'lib/__init__.py' '__version__' +24.0us
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:history <re.Match object; span=(0, 21), match='__version__ = "1.0.0"'> +283.25us
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:cli 'publish: retry=' False +669.75us
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:history:logs 'evaluate_version_bump("1.0.0", "None")' +0.0us
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:vcs_helpers 'Reference v1.0.0 does not exist, considering all log' +0.0us
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:history:logs 'ignored' UnknownCommitMessageStyleError('Unable to parse the given commit message: Provide new directory option to actions\n') +9.4ms
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:history 'get_new_version("1.0.0", "None")' +9.7ms
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:vcs_helpers 'get_repository_owner_and_name' <re.Match object; span=(18, 55), match='/somerepo/my-project-name'> +10.1ms
Fri, 14 Feb 2020 14:35:58 GMT semantic_release:cli 'branch=' 'master' +10.6ms
Cmd('git') failed due to: exit code(1)
  cmdline: git checkout master
  stderr: 'error: pathspec 'master' did not match any file(s) known to git'
##[error]Docker run failed with exit code 1
```

Not sure why it is trying to checkout master branch if I am trying to set it on some experimental branch.

**Comment by AlphaMycelium** [comment] 2020-02-14 15:33
@KingDarBoja Yeah, if the commit message doesn't follow the convention then no new version will be published.

**Comment by KingDarBoja** [comment] 2020-02-14 15:45
@AlphaMycelium Makes sense, I just tried it again and the `UnknownCommitMessageStyleError` got away but still no new version being published.

I saw at your example, you provide something like this at you `setup.cfg`:

```
[semantic_release]
version_variable=paa/__init__.py:__version__
version_source=tag
```

But the `__version__` isn't there, that's on purpose? What about the `setup.py` file without specifying the `version=version` value?

**Comment by AlphaMycelium** [comment] 2020-02-14 16:02
@KingDarBoja I'm using [setuptools-scm](https://github.com/pypa/setuptools_scm/#setuppy-usage) to get the version from Git tags instead of explicitly defining it in `setup.py` and `__init__.py`. This is to avoid having a commit created every time a new release is published. That's why I also set `version_source=tag`. I only include `version_variable` in `setup.cfg` because semantic release was throwing errors if I didn't, as far as I know it's never actually used.

**Comment by KingDarBoja** [comment] 2020-02-14 16:07
Looks like the error is coming from `get_commit_log()` function at [vsc_helperts](https://python-semantic-release.readthedocs.io/en/latest/_modules/semantic_release/vcs_helpers.html) but not sure why!

**Comment by AlphaMycelium** [comment] 2020-02-14 16:09
@KingDarBoja It looks like it's trying to find commits which occur after the `v1.0.0` tag, but that doesn't exist, so it looks at the entire commit history instead.

**Comment by KingDarBoja** [comment] 2020-02-14 16:19
I am using the `version_source` as `commit` instead of `tag` and set `commit_version_number=true`. Maybe it is the reason it doesn't work? 🤔

**Comment by AlphaMycelium** [comment] 2020-02-14 19:47
> One problem I'm having is that the release notes are replaced with a short message containing only the name of the tag, as seen [here](https://github.com/AlphaMycelium/chicken-nuggets/releases/tag/v1.0.1).

Since KingDarBoja's release notes are working, I think the problem I'm having with them is something specific to my own setup and not caused by GitHub Actions.

@KingDarBoja For reference, are you using the preset `GITHUB_TOKEN` secret as shown in [my example configuration](https://github.com/AlphaMycelium/psr-action#example-workflow), or a separate personal access token?

**Comment by KingDarBoja** [comment] 2020-02-14 20:30
@AlphaMycelium I use the same preset as the example. Maybe the behaviour doesn't work at all if you set `version_source=tag` instead of `commit`.

I can't share too much about the project but below are the `actions.yml` file and my `setup.cfg`:

**custom-action.yml**
```yml
name: my test release

on:
 push:
   branches:
     - experimental-branch

jobs:
 release:
   name: some release name
   runs-on: ubuntu-latest

   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
       with:
         ref: experimental-branch

     - name: Release Package Core
       uses: AlphaMycelium/psr-action@master
       with:
         directory: ./core
         github_token: ${{ secrets.GITHUB_TOKEN }}
```

**config.cfg**
```config
[semantic_release]
version_variable=subfoldercore/__init__.py:__version__
version_source=commit
commit_version_number=true
upload_to_pypi=false
branch=experimental-branch
```

**Comment by AlphaMycelium** [comment] 2020-02-14 22:32
@KingDarBoja Hmmm. I was just wondering if it was some sort of permissions thing with the automatically-generated token, but it can't be if you're using that too and it works.

**Comment by AlphaMycelium** [comment] 2020-04-13 13:33
This is now finished and implemented within the main repository (instead of the separate `psr-action`), see the [documentation page](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html) for details on setting it up.

**Closed by AlphaMycelium** 2020-04-13 13:33 UTC
Labels: feature, needs-docs, ★★
