### ISSUE TITLE
Add links to commits in generated changelog

### ISSUE THREAD

**Issue by honzajavorek** [relekang/python-semantic-release#63] opened 2016-11-05 13:56 UTC
The problem with current changelog is that it nicely lists changes, but if one sentence isn't enough for the reader to understand what exactly happened, they have to go and dig up the change somewhere from git history. That's pretty inconvenient.

What JS version of semantic releasing does is it adds link to the particular commit:

<img width="758" alt="image" src="https://cloud.githubusercontent.com/assets/283441/20030564/21271bb2-a368-11e6-9aa2-8bc652bc5157.png">

**Comment by blackHatMonkey** [comment] 2017-04-24 18:42
@relekang I would like to help implement his. Can you point me to the section of the code that should modified?

**Comment by relekang** [comment] 2017-04-25 05:57
@blackHatMonkey Cool 🙂 [generate_changelog](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/history/logs.py#L56) is a goo place to start. If we add that info to the lists there and then output it [markdown_changelog](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/history/logs.py#L106) I think it would work nicely.

**Comment by blackHatMonkey** [comment] 2017-04-25 12:15
@relekang I was looking in `generate_changelog` and I came cross [this](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/history/logs.py#L86):
```python
message = current_commit_parser()(commit_message)
```
Is that a bug? I'm asking since I have never seen syntax like that.

**Comment by relekang** [comment] 2017-04-25 12:46
It is not a bug, `current_commit_parser` is a function that returns a parser that happens to be a function. The line calls the returned parser with the commit message.

The two snippets below gives the same result.

```python
message = current_commit_parser()(commit_message)
```

```python
parser = current_commit_parser()
message = parser(commit_message)
```

**Comment by blackHatMonkey** [comment] 2017-04-25 14:41
@relekang To be honest the second one looks more understandable to a person from the outside. Anyway I have looked through the code with `pdb` and now have a good understanding of it. Where do you think would be the best place for it to add the commit version?
I was thinking maybe in the `changes` or it could be in the `markdown_changelog`?

**Comment by relekang** [comment] 2017-04-25 19:49
> To be honest the second one looks more understandable to a person from the outside. 

Feel free to change it 🙂

> I was thinking maybe in the changes or it could be in the markdown_changelog?

Firstly we should make [`get_commit_log`](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/vcs_helpers.py#L19) yield a tuple of git hash and commit message.

Then that needs to be handled inside `generate_changelog` and print it in `markdown_changelog`.

**Comment by blackHatMonkey** [comment] 2017-04-25 20:54
> Then that needs to be handled inside generate_changelog

What do you have in mind?

**Comment by relekang** [comment] 2017-04-28 06:28
There is a for loop there that iterates over the results yielded from `get_commit_log`. It needs to unpack `for hash, commit_message in get_commit_log(rev):`. Then all places where we append changes we should make add the commit hash and message as a tuple.

**Comment by blackHatMonkey** [comment] 2017-05-05 17:17
@relekang I have implemented this feature in #65. Let me know if I need to change anything :smile: .

**Comment by relekang** [comment] 2017-05-05 18:35
Thanks ✌️

**Comment by relekang** [comment] 2017-05-05 19:25
It is out as [v3.10.0](https://github.com/relekang/python-semantic-release/releases/tag/v3.10.0). It was released using the master branch of this repo so the release has nice commit links 🎉

**Comment by blackHatMonkey** [comment] 2017-05-06 22:31
@relekang I believe you can just close this issue :smile: .

**Closed** 2017-05-07 06:35 UTC
Labels: feature, help-wanted
