### ISSUE TITLE
Gitlab CI automatic release

### ISSUE THREAD

**Issue by nraw** [relekang/python-semantic-release#326] opened 2021-02-18 12:24 UTC
## The problem
I'm trying to set up gitlab ci to work with pythonn-semantic-release but when the code tries to push, I'm getting 403 Forbidden.

## Expected behavior
python-semantic-release would realise it's on gitlab ci and obtain the CI_JOB_TOKEN.

## Additional context
Could it be connected to this: https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html

Are there any examples out there of `.gitlab-ci.yml` for this use case?

**Comment by danth** [comment] 2021-02-18 12:30
Could you run Python Semantic Release with `--verbosity=DEBUG` and upload the log please?

**Comment by nraw** [comment] 2021-02-18 12:41
```
debug: get_current_version_by_config_file()
debug: Parsing current version: path='pyproject.toml' pattern='version = "(\\d+\\.\\d+\\.\\d+)"' num_matches=1
debug: Regex matched version: 1.3.0
debug: get_current_version_by_config_file -> 1.3.0
debug: evaluate_version_bump('1.3.0', None)
debug: parse_commit_message('ci: verbosity')
debug: parse_commit_message -> ParsedCommit(bump=0, type='ci', scope=None, descriptions=['verbosity'], breaking_descriptions=[])
debug: parse_commit_message('ci: job token')
debug: parse_commit_message -> ParsedCommit(bump=0, type='ci', scope=None, descriptions=['job token'], breaking_descriptions=[])
debug: parse_commit_message('feat: massive feature')
debug: parse_commit_message -> ParsedCommit(bump=2, type='feature', scope=None, descriptions=['massive feature'], breaking_descriptions=[])
debug: parse_commit_message('ci: testing release again')
debug: parse_commit_message -> ParsedCommit(bump=0, type='ci', scope=None, descriptions=['testing release again'], breaking_descriptions=[])
debug: Commits found since last release: 4
debug: evaluate_version_bump -> minor
debug: get_new_version('1.3.0', 'minor')
debug: get_new_version -> 1.4.0
debug: get_repository_owner_and_name()
debug: get_repository_owner_and_name -> ('ANONYMISED_GROUP', 'test4')
debug: Running publish on branch master
debug: checkout('master')
debug: checkout -> Branch 'master' set up to track remote branch 'master' from 'origin'.
debug: generate_changelog('1.3.0')
debug: parse_commit_message('ci: verbosity')
debug: parse_commit_message -> ParsedCommit(bump=0, type='ci', scope=None, descriptions=['verbosity'], breaking_descriptions=[])
debug: Creating new changelog section for ci 
debug: parse_commit_message('ci: job token')
debug: parse_commit_message -> ParsedCommit(bump=0, type='ci', scope=None, descriptions=['job token'], breaking_descriptions=[])
debug: parse_commit_message('feat: massive feature')
debug: parse_commit_message -> ParsedCommit(bump=2, type='feature', scope=None, descriptions=['massive feature'], breaking_descriptions=[])
debug: Creating new changelog section for feature 
debug: parse_commit_message('ci: testing release again')
debug: parse_commit_message -> ParsedCommit(bump=0, type='ci', scope=None, descriptions=['testing release again'], breaking_descriptions=[])
debug: generate_changelog -> {'breaking': [], 'ci': [('45661081eea5c9fe324d0bb4010b9499a1da98f1', 'Verbosity'), ('3b1b7233432ffc0baf883317813898a4bb4ec646', 'Job token'), ('81c3d00446e2606e24acb41b0c2c8d07d415718d', 'Testing release again')], 'feature': [('de27fdef5d4faec506b10d371f50e14629a20422', 'Massive feature')]}
debug: markdown_changelog('ANONYMISED_GROUP', 'test4', '1.4.0', {'breaking': [], 'ci': [('45661081eea5c9fe324d0bb4010b9499a1da98f1', 'Verbosity'), ('3b1b7233432ffc0baf883317813898a4bb4ec646', 'Job token'), ('81c3d00446e2606e24acb41b0c2c8d07d415718d', 'Testing release again')], 'feature': [('de27fdef5d4faec506b10d371f50e14629a20422', 'Massive feature')]}, header=False, previous_version='1.3.0')
debug: markdown_changelog -> ### Feature
debug: * Massive feature ([`de27fde`](https://git.ANONYMISED.com/ANONYMISED_GROUP/test4/-/commit/de27fdef5d4faec506b10d371f50e14629a20422))
debug: update_changelog_file('1.4.0', '### Feature
debug: * Massive feature ([`de27fde`](https://git.ANONYMISED.com/ANONYMISED_GROUP/test4/-/commit/de27fdef5d4faec506b10d371f50e14629a20422))')
debug: set_new_version('1.4.0')
debug: Writing new version number: path='pyproject.toml' pattern='version = "(\\d+\\.\\d+\\.\\d+)"' num_matches=1
debug: set_new_version -> True
debug: commit_new_version('1.4.0')
debug: commit_new_version -> [master a385816] build: 1.4.0
debug:  Author: semantic-release <semantic-release>
debug:  2 files changed, 5 insertions(+), 1 deletion(-)
debug: tag_new_version('1.4.0')
debug: tag_new_version -> 
Bumping with a minor version to 1.4.0
Pushing new version
debug: get_hvcs()
debug: get_hvcs -> <class 'semantic_release.hvcs.Gitlab'>
debug: get_hvcs()
debug: get_hvcs -> <class 'semantic_release.hvcs.Gitlab'>
debug: push_new_version(, auth_token=None, owner='ANONYMISED_GROUP', name='test4', branch='master', domain='git.ANONYMISED.com')
error: Cmd('git') failed due to: exit code(128)
error:   cmdline: git push origin master
error:   stderr: 'remote: You are not allowed to upload code.
error: fatal: unable to access 'https://gitlab-ci-token:[MASKED]@git.ANONYMISED.com/ANONYMISED_GROUP/test4.git/': The requested URL returned error: 403'
```

The Anonymised are manually replaced by me. the [MASKED] is masked already in the logs.

**Comment by nraw** [comment] 2021-02-18 12:55
For starters, it seems like the token asked for is [GL_TOKEN](https://github.com/relekang/python-semantic-release/blob/77ad988a2057be59e4559614a234d6871c06ee37/semantic_release/hvcs.py#L371), but the token passed by CI is `CI_JOB_TOKEN`. I'll try to define `GL_TOKEN: ${CI_JOB_TOKEN}` as a variable in the pipeline

**Comment by chbndrhnns** [comment] 2021-02-18 14:30
IIRC, pushing code with this `CI_JOB_TOKEN` is [not possible](https://docs.gitlab.com/ee/api/README.html#gitlab-ci-job-token) and a personal access token is required for that.

**Comment by danth** [comment] 2021-02-19 11:57
As far as I can see, this is caused by `CI_JOB_TOKEN`'s permissions and not a bug in Python Semantic Release. I'm not familiar with GitLab so I won't be able to help with this issue.

If you find a solution, please comment here so it can be added to the documentation.

**Comment by carlosfunk** [comment] 2021-02-24 23:02
@nraw I've just been through the same thing, you need to create a personal access token and use that to set a CI/CD variable called GL_TOKEN.

**Comment by relekang** [comment] 2021-03-26 12:59
Closing this as it seems to be a config problem.

**Closed by relekang** 2021-03-26 12:59 UTC
Labels: bug, help-wanted

**Comment by gabrielSoudry** [comment] 2021-09-09 16:45
You need to set:  hvcs gitlab

[semantic_release]
version_variable = gotomate/__init__.py:__version__
hvcs=gitlab
