### ISSUE TITLE
CircleCI always fails on PR with a false negative

### ISSUE THREAD

**Issue by esciara** [relekang/python-semantic-release#131] opened 2019-06-11 09:11 UTC
An example can be found [here](https://circleci.com/gh/esciara/python-semantic-release/39?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

```
=================================== FAILURES ===================================
______________________ test_publish_should_call_functions ______________________

mocker = <pytest_mock.MockFixture object at 0x7f0f54183eb8>
runner = <click.testing.CliRunner object at 0x7f0f54183e10>

    def test_publish_should_call_functions(mocker, runner):
        mock_push = mocker.patch('semantic_release.cli.push_new_version')
        mock_checkout = mocker.patch('semantic_release.cli.checkout')
        mock_version = mocker.patch('semantic_release.cli.version', return_value=True)
        mock_log = mocker.patch('semantic_release.cli.post_changelog')
        mock_ci_check = mocker.patch('semantic_release.ci_checks.check')
        mock_pypi = mocker.patch('semantic_release.cli.upload_to_pypi')
        mocker.patch('semantic_release.cli.evaluate_version_bump', lambda *x: 'feature')
        mocker.patch('semantic_release.cli.generate_changelog')
        mocker.patch('semantic_release.cli.markdown_changelog', lambda *x, **y: 'CHANGES')
        mocker.patch('semantic_release.cli.get_new_version', lambda *x: '2.0.0')
        mocker.patch('semantic_release.cli.check_token', lambda: True)
        result = runner.invoke(main, ['publish'])
        assert result.exit_code == 0
        assert mock_ci_check.called
        assert mock_push.called
        assert mock_pypi.called
        mock_version.assert_called_once_with(noop=False, post=False, force_level=None, retry=False)
>       mock_log.assert_called_once_with(u'relekang', 'python-semantic-release', '2.0.0', 'CHANGES')
E       AssertionError: Expected call: post_changelog('relekang', 'python-semantic-release', '2.0.0', 'CHANGES')
E       Actual call: post_changelog('esciara', 'python-semantic-release', '2.0.0', 'CHANGES')
E       
E       pytest introspection follows:
E       
E       Args:
E       assert ('esciara', '...0', 'CHANGES') == ('relekang', '...0', 'CHANGES')
E         At index 0 diff: 'esciara' != 'relekang'
E         Full diff:
E         - ('esciara', 'python-semantic-release', '2.0.0', 'CHANGES')
E         ?    ^^^ ^^
E         + ('relekang', 'python-semantic-release', '2.0.0', 'CHANGES')
E         ?   + ^^^ ^^

tests/test_cli.py:248: AssertionError
______________________ test_get_repository_owner_and_name ______________________

    def test_get_repository_owner_and_name():
>       assert get_repository_owner_and_name()[0] == 'relekang'
E       AssertionError: assert 'esciara' == 'relekang'
E         - esciara
E         + relekang

tests/test_vcs_helpers.py:44: AssertionError
```

Tests are expecting author to be `relekang` whereas it is correct that it is `esciara`.

**Comment by esciara** [comment] 2019-06-11 10:01
Actually, this is a reddit of #108.

**Comment by relekang** [comment] 2019-06-12 08:33
Closing this as duplicate of #108

**Closed by relekang** 2019-06-12 08:33 UTC
