### ISSUE TITLE
Workflows with python-semantic-release broke on 03.05.22

### ISSUE THREAD

**Issue by eifinger** [relekang/python-semantic-release#442] opened 2022-05-03 06:16 UTC
## The problem

All my repo have a nightly scheduled workflow. I noticed that all which use this Github Action broke tonight. I struggle to find what the actual error is. Here is one example where the workflow broke: https://github.com/eifinger/hass-here-weather/runs/6267125839?check_suite_focus=true
I am running on the master branch so I think [the latest commit](https://github.com/relekang/python-semantic-release/commit/94c94942561f85f48433c95fd3467e03e0893ab4) broke something.

## Expected behavior

The Github Action starts, checks commits, sees there is nothing to do and exits successfully.

## Additional context

* [Workflow Config](https://github.com/eifinger/hass-here-weather/blob/main/.github/workflows/ci.yml)
* [Semantic Release Config](https://github.com/eifinger/hass-here-weather/blob/main/pyproject.toml#L77-L85)

**Comment by martolini** [comment] 2022-05-03 08:14
Experiencing the same issue, here.

**Comment by ngshiheng** [comment] 2022-05-05 13:00
I dived a little bit deeper into this issue, and here's what I found:
- The most recent PR that was merged https://github.com/relekang/python-semantic-release/pull/435 seems to be causing this issue
- The issue seems to be related to the regex used here at https://github.com/relekang/python-semantic-release/blob/94c94942561f85f48433c95fd3467e03e0893ab4/semantic_release/history/__init__.py#L377
- From my observation and tests, `get_current_release_version_by_commits` seems to be parsing version incorrectly from commit messages
- To confirm it was a regex issue, I was using ([Pythex link](https://pythex.org/?regex=(%5Cd%2B%5C.%5Cd%2B%5C.%5Cd%2B(%3F!-beta%5C.%5Cd%2B))&test_string=chore(deps)%3A%20update%20dependency%20pylint%20to%20v2.13.8%0Afix(deps)%3A%20update%20dependency%20pylint%20to%20v2.13.8%0Afix(deps)%3A%20update%20dependency%20sqlalchemy%20to%20v1.4.36%0A1.4.1%0A0.3.5-beta.0&ignorecase=0&multiline=0&dotall=0&verbose=0))

**Comment by H0R5E** [comment] 2022-05-17 13:34
I also had a failure when using the emoji parser. The commit message `:children_crossing: Bump to version 0.5.0` resulted in this log output then a crash:

```
Run relekang/python-semantic-release@master
/usr/bin/docker run --name d08de0a8fc1f74f69a8a345b5ff0901fc_845cdf --label 08450d --workdir /github/workspace --rm -e GIT_COMMIT_SHA -e GIT_COMMIT_SHORT_SHA -e GIT_COMMIT_AUTHOR -e GIT_COMMIT_AUTHOR_NAME -e GIT_COMMIT_AUTHOR_EMAIL -e GIT_COMMIT_COMMITTER -e GIT_COMMIT_COMMITTER_NAME -e GIT_COMMIT_COMMITTER_EMAIL -e GIT_COMMIT_MESSAGE_SUBJECT -e GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED -e GIT_COMMIT_MESSAGE_BODY -e INPUT_GITHUB_TOKEN -e INPUT_REPOSITORY_USERNAME -e INPUT_REPOSITORY_PASSWORD -e INPUT_DIRECTORY -e INPUT_PYPI_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/convergence/convergence":"/github/workspace" 08450d:08de0a8fc1f74f69a8a345b5ff0901fc
debug: get_current_version_by_config_file()
debug: Parsing current version: path=PosixPath('setup.cfg') pattern='version = (\\d+\\.\\d+\\.\\d+)' num_matches=1
debug: Regex matched version: 0.4.2
debug: get_current_version_by_config_file -> 0.4.2
debug: get_current_release_version_by_commits()
debug: Checking commit 1334a075[19](https://github.com/Data-Only-Greater/convergence/runs/6470883219?check_suite_focus=true#step:7:19)1[22](https://github.com/Data-Only-Greater/convergence/runs/6470883219?check_suite_focus=true#step:7:22)c[27](https://github.com/Data-Only-Greater/convergence/runs/6470883219?check_suite_focus=true#step:7:27)04[30](https://github.com/Data-Only-Greater/convergence/runs/6470883219?check_suite_focus=true#step:7:30)af1845d4b09c72f6ae[34](https://github.com/Data-Only-Greater/convergence/runs/6470883219?check_suite_focus=true#step:7:34)
debug: Version matches regex :children_crossing: Bump to version 0.5.0
debug: get_current_release_version_by_commits -> 0.5.0
Current version: 0.4.2, Current release version: 0.5.0
debug: evaluate_version_bump('0.4.2', None)
debug: parse_commit_message(':children_crossing: Bump to version 0.5.0')
debug: Selected :children_crossing: as the primary emoji
debug: parse_commit_message -> ParsedCommit(bump=2, type=':children_crossing:', scope=None, descriptions=[':children_crossing: Bump to version 0.5.0 '], breaking_descriptions=[])
debug: parse_commit_message('Add Python 3.10 support and remove Python 3.6 (#13)')
debug: Selected Other as the primary emoji
debug: parse_commit_message -> ParsedCommit(bump=0, type='Other', scope=None, descriptions=['Add Python 3.10 support and remove Python 3.6 (#13)'], breaking_descriptions=[])
debug: Commits found since last release: 2
debug: evaluate_version_bump -> minor
debug: get_new_version('0.4.2', '0.5.0', 'minor', False)
```

I've pinned semantic release to version 7.28.1 as a workaround:

```yml
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@v7.28.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
```

**Comment by SoundsSerious** [comment] 2022-05-18 01:08
same here, not sure what to do about it besides downgrade

**Comment by SoundsSerious** [comment] 2022-05-18 01:14
I can confirm @H0R5E's downgrade works

**Comment by sbrugman** [comment] 2022-05-27 14:58
Same issue here. `python-semantic-release` picked up the version of another package that was linked in one of the commits.

**Comment by ajite** [comment] 2022-06-02 03:08
Same issue here. The downgrade worked.

**Comment by mrlubos** [comment] 2022-06-07 23:10
+1

**Comment by browniebroke** [comment] 2022-07-14 22:35
I've pinned PSR to be <7.29 as well, but unfortunately this is also affected by the recent issue with `packaging` (#468). People in this thread were correct, it's a version parsing issue when one of the commits contain a version bump. I think I fixed it in https://github.com/relekang/python-semantic-release/pull/472

If folks want to try it out, you can change the GitHub action to: 

```
uses: browniebroke/python-semantic-release@fix/version-parsing-commit
```

Just tested it on one of my projects and it worked: https://github.com/browniebroke/deezer-oauth-cli/runs/7349125319?check_suite_focus=true#step%3A4%3A235=

**Comment by ajite** [comment] 2022-07-19 01:57
@browniebroke thanks. I tried on it on one of my repo and it works.

**Comment by chanind** [comment] 2022-07-23 22:42
For some reason @browniebroke's fix didn't work for me. I had to branch off the 7.28.1 release and manually add the `packaging` fix in. In case it's useful for anyone else my fork can be used in a github action with `uses: chanind/python-semantic-release@7-28-1-packaging-fix`

**Comment by eifinger** [comment] 2022-07-23 22:51
@chanind what didn't work for you with my fix.

**Comment by chanind** [comment] 2022-07-23 23:40
I didn't try your version, I just tried `browniebroke/python-semantic-release@fix/version-parsing-commit`. You can see the output here, I'm not sure why it didn't work but it had the same issue with incorrectly parsing version from commits: https://github.com/chanind/fuzzy-reasoner/runs/7480887304?check_suite_focus=true

**Comment by browniebroke** [comment] 2022-07-24 09:18
Looks like it worked with @eifinger version: https://github.com/chanind/fuzzy-reasoner/runs/7480950131?check_suite_focus=true#step%3A4%3A244=

I'll close my PR and edit my comment to avoid confusion

**Comment by chanind** [comment] 2022-07-24 09:49
I didn't try the eifinger version - that link is using chanind/python-semantic-release@7-28-1-packaging-fix.

**Closed** 2022-07-24 15:41 UTC
Labels: bug
